Hunter 3.4.1
hunter-packages/opencv pull request #22
Opened 2018-02-27 04:39 UTC by xsacha

2018-02-27 08:03 UTC, ruslo requested changes

2018-02-27 08:03 UTC, ruslo commented on modules/java/android_test/CMakeLists.txt
> +if(NOT ANT_EXECUTABLE OR NOT ANDROID_EXECUTABLE OR NOT ANDROID_TOOLS_Pkg_Revision GREATER 13)
It seems that this file is not present in original code anymore.

2018-02-27 08:03 UTC, ruslo commented on modules/ts/misc/run_utils.py
> +    {'name': "git_executable",           'default': None,       'pattern': re.compile(r"^GIT_EXECUTABLE:FILEPATH=(.*)$")},
I think rework needed here, there is no `git_executable` part in OpenCV 3.4.1 version for example.

2018-02-27 08:19 UTC, xsacha commented
Oh, I will check those again.

2018-02-27 23:53 UTC, xsacha commented
Didn't handle that merge conflict properly so I rebased again.
That should work fine now :)

2018-02-28 00:12 UTC, ruslo approved these changes
Looks good, thank you.

2018-02-28 00:12 UTC, merged

2018-02-28 00:13 UTC, ruslo commented
Released: https://github.com/hunter-packages/opencv/releases/tag/v3.4.1-p0